version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout

      - run:
          name: Install packages
          command: sudo apt-get update && sudo apt-get install wget zip unzip python2.7 python-pip -y

      - run:
          name: Install awscli
          command: |
            sudo pip install awscli
            aws configure set aws_access_key_id ${aws_access_key_id}
            aws configure set aws_secret_access_key ${aws_secret_access_key}
            aws configure set region us-east-1
            aws configure list
      - run:
          name: Build Artifact
          command: |
            cd Lambda
            pwd
            ls -al
            mvn clean install
            cd target/
            ls -al
            cd ../
            pwd
            ls -al
      - run:
          name: Zip Artifact
          command: |
            echo "current build number is ${CIRCLE_BUILD_NUM}"
            pwd
            mkdir -p codedeploy_artifact
            cd codedeploy_artifact
            cp ../Lambda/target/Lambda-0.0.1-SNAPSHOT.jar .
            ls -al
            pwd
            cd ..
            pwd
            ls -al
      - run:
          name: Upload Artifact to S3
          command: |
            aws s3 cp --recursive codedeploy_artifact s3://${CODE_DEPLOY_S3_BUCKET}
      - run:
          name: Make CodeDeploy API call
          command: |
            echo "Hello"

workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master